// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zlidmqinnvyjtffczyhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsaWRtcWlubnZ5anRmZmN6eWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NjE3NzIsImV4cCI6MjA3NTMzNzc3Mn0.mHQYBRv_Ph2O2qmOIXg5zOjAlv0f3WUN0A_1UBE4DDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);